### ISSUE TITLE
Eseleges igény

### ISSUE THREAD

**Issue by HBarbara** [burgatshow/mileit#81]
Szia!

Ha lehet, kérnék szépen a programhoz biztonsági mentési és exportálási lehetőséget 
Valamint az autók menü pontba egyéb ktg-ek felviteléhez (biztosítások, autópályadíjak, parkolási díjak, adók, bírságok) opciót

Köszönöm szépen! Sok sikert és kitartást! 🤗

**Comment by burgatshow** [comment]
Closing, reqested features splitted, see #82 #83.

Follow status there, this request is closed.
